version: '3'

services:
  nextcloud_db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - cloudnet
    volumes:
      - ./nextcloud-db:/var/lib/mysql
    env_file:
      - .env

  nextcloud:
    build:
      context: .
      target: nc
    restart: always
    networks:
      - cloudnet
    ports:
      - 8088:80
    volumes:
      - ./nextcloud-docroot:/var/www/html
    env_file:
      - .env

  nextcloud_redis:
    image: redis:alpine
    restart: always
    networks:
      - cloudnet

networks:
  cloudnet:
    name: cloudnet
    driver: bridge
