version: '3.8'

services:
  db:
    image: mysql:8.0.31
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - nextcloud

  app:
    image: nextcloud:24.0.6-fpm
    build: .
    links:
      - db
    volumes:
      - ./nextcloud:/var/www/html:z
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    networks:
      - nextcloud

  web:
    image: nginx
    ports:
      - 80:80
    links:
      - app
    volumes:
      - ./nextcloud:/var/www/html:z
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: always
    networks:
      - nextcloud

networks:
  nextcloud:


volumes:
  nextcloud:
  db:
